### ISSUE TITLE
デプロイ方法について相談

### ISSUE THREAD

**Issue by femshima** [discordjs-japan/om#10]
デプロイ方法はscripts/register.tsを実行するのだろうと推測していますが，誰がいつ実行するのがよいでしょうか．

GitHub Actionsで実行した場合，（GitHub ActionsでSSH接続してデプロイしない限り）デプロイが行われるまでの間は一部のコマンドが使えない状態になります．その時間が短ければtagをトリガーにできますが，長いようであれば手動でトリガーする必要があり，それではローカルで実行するのとあまり変わらないのでは．

**Comment by Mogyuchi** [comment]
起動時に Bulk Overwrite Global Application Commands を叩くアプローチにしましょう
