### ISSUE TITLE
Node.js v20 にする。？

### ISSUE THREAD

**Issue by Mogyuchi** [discordjs-japan/om#18]

**Comment by femshima** [comment]
`@discordjs/opus`にNode 20用のprebuildがないので，クロスコンパイルが要りそうですが…

**Comment by cm-ayf** [comment]
https://discord.com/channels/391390986770710528/391392898853371915/1178126555449401395

**Comment by cm-ayf** [comment]
https://github.com/discordjs/opus/pull/148

**Comment by cm-ayf** [comment]
#22
